server:
  port: 8080

spring:
  datasource:
    url: dbc:h2:mem:speciality_database
    username: speciality-app
    password: speciality-app!
    driver-class-name: org.h2.Driver

logging:
  file:
    name: ./logs/speciality-app.log